version: 2

sources:
  - name: sap_adw
    database: adw-project-431916
    schema: sap_adw
    description: this is Adventure Works SAP database
    tables:
      - name: store
        description: table with informations about the stores that use to buy on Adventure Works
        columns:
          - name: businessentityid
            description: primary key of store
            tests:
              - unique
              - not_null

      - name: customer
        description: main table of customers of Adventure Works
        columns:
          - name: customerid
            description: primary key of customers
            tests:
              - unique
              - not_null
          - name: storeid
            description: foreign key for store
            tests:
              - relationships:
                  field: businessentityid
                  to: ref('stg_store')
          - name: personid
            description: foreign key for person
            tests:
              - relationships:
                  field: businessentityid
                  to: ref('stg_person')

      - name: person
        description: main table of informations about all persons related to Adventure Works, including employees and customers
        columns:
          - name: businessentityid
            description: primary key of person
            tests:
              - unique
              - not_null

      - name: personcreditcard
        description: table mapping people to their credit card information
        columns:
          - name: businessentityid
            description: primary key of person credit card
            tests:
              - unique
              - not_null
          - name: creditcardid
            description: Foreign key for credit card
            tests:
              - relationships:
                  field: creditcardid
                  to: ref('stg_creditcard')

      - name: creditcard
        description: table with credit card infomation
        columns:
          - name: creditcardid
            description: primary key of credit card
            tests:
              - unique
              - not_null

      - name: employee
        description: table to link  person table with sales person
        columns:
          - name: businessentityid
            description: primary key of employee
            tests:
              - unique
              - not_null

      - name: salesperson
        description: Sales person table
        columns:
          - name: businessentityid
            description: primary key of sales person
            tests:
              - unique
              - not_null
          - name: territoryid
            description: foreign key for sales territory
            tests:
              - relationships:
                  field: territoryid
                  to: ref('stg_salesterritory')

      - name: address
        description: table with address information for each sale
        columns:
          - name: addressid
            description: primary key of address table
            tests:
              - unique
              - not_null
          - name: stateprovinceid
            description: Foreign key for state province
            tests:
              - relationships:
                  field: stateprovinceid
                  to: ref('stg_stateprovince')

      - name: stateprovince
        description: table with name of the state or province for each sale
        columns:
          - name: stateprovinceid
            description: primary key of state province table
            tests:
              - unique
              - not_null
          - name: countryregioncode
            description: foreign key for store table
            tests:
              - relationships:
                  field: countryregioncode
                  to: ref('stg_countryregion')

      - name: countryregion
        description: table with name of the country for each sale
        columns:
          - name: countryregioncode
            description: primary key of country region table
            tests:
              - unique
              - not_null

      - name: salesterritory
        description: Sales territory table
        columns:
          - name: territoryid
            description: primary key of sales territory table
            tests:
              - unique
              - not_null

      - name: salesorderheader
        description: main table of sales
        columns:
          - name: salesorderid
            description: primary key of sales order header table
            tests:
              - unique
              - not_null
          - name: customerid
            description: foreign key for customer
            tests:
              - relationships:
                  field: customerid
                  to: ref('stg_customer')
          - name: salespersonid
            description: Foreign key for sales person
            tests:
              - relationships:
                  field: businessentityid
                  to: ref('stg_salesperson')
          - name: shiptoaddressid
            description: foreign key for address
            tests:
              - relationships:
                  field: addressid
                  to: ref('stg_address')
          - name: creditcardid
            description: foreign key for credit card
            tests:
              - relationships:
                  field: creditcardid
                  to: ref('stg_credticard')
          - name: territoryid
            description: Foreign key for sales territory
            tests:
              - relationships:
                  field: territoryid
                  to: ref('stg_salesterritory')

      - name: salesorderdetail
        description: table with sales detail
        columns:
          - name: salesorderdetailid
            description: primary key of sales order detail table
            tests:
              - unique
              - not_null
          - name: salesorderid
            description: foreign key for sales order
            tests:
              - relationships:
                  field: salesorderid
                  to: ref('stg_salesorderheader')
          - name: productid
            description: foreign key for product
            tests:
              - relationships:
                  field: productid
                  to: ref('stg_product')

      - name: product
        description: main product table
        columns:
          - name: productid
            description: primary key of product table
            tests:
              - unique
              - not_null
          - name: productsubcategoryid
            description: Foreign key for product subcategory
            tests:
              - relationships:
                  field: productsubcategoryid
                  to: ref('stg_productsubcategory')

      - name: productsubcategory
        description: Subcategory description of all products
        columns:
          - name: productsubcategoryid
            description: primary key of product subcategory table
            tests:
              - unique
              - not_null
          - name: productcategoryid
            description: Foreign key for product category
            tests:
              - relationships:
                  field: productcategoryid
                  to: ref('stg_productcategory')

      - name: productcategory
        description: Category description of all products
        columns:
          - name: productcategoryid
            description: primary key of product category table
            tests:
              - unique
              - not_null

      - name: salesorderheadersalesreason
        description: Table to link sales reason to sales order header
        columns:
          - name: salesorderid
            description: Foreign key for sales order header
            tests:
              - relationships:
                  field: salesorderid
                  to: ref('stg_salesorderheader')
          - name: salesreasonid
            description: Foreign key for sales reason
            tests:
              - relationships:
                  field: salesreasonid
                  to: ref('stg_salesreason')

      - name: salesreason
        description: Table with sales reason information
        columns:
          - name: salesreasonid
            description: primary key of sales reason table
            tests:
              - unique
              - not_null